### ISSUE TITLE
Community section needs an update on where to file documentation bugs

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterweb#134]
I believe we need to update,  glusterweb/source/community/index.html.haml to point to glusterdocs github repository for users to file issues against documentation on github.

Right now it points to Bugzilla to file issues against documentation. ("...Report a problem in Documentation", "https://bugzilla.redhat.com/enter_bug.cgi?product=Gluster-Documentation" )

I can submit a PR if this seems right.

**Comment by amye** [comment]
Honestly, I like the Github issues better - having to have a login to file a bug when the documentation is now open is just silly. Actually this is on the front page, not just the community page. 

PR welcome if I don't get to this in the next two days.

**Comment by amye** [comment]
This is fixed in new content. Hurray!
