### ISSUE TITLE
Inconsistent 'Read More' buttons

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterweb#150]
![screenshot_20170901_153856](https://user-images.githubusercontent.com/362086/29965560-ad25253c-8f2b-11e7-81e4-933cbee80b85.png)

The third Read More button in the screen shot is inconsistently styled. This is from the new site.

**Comment by amye** [comment]
This is probably going to need someone with WP theming expertise to fix. @tigert, can you help on this one?

**Comment by kshlm** [comment]
This seems to have fixed itself. I don't see the inconsistency anymore.
