### ISSUE TITLE
Terms of Service on gluster.org have been copy/pasted from Ceph

### ISSUE THREAD

**Issue by nixpanic** [gluster/glusterweb#152]
The contents on https://www.gluster.org/legal-page/terms-of-service/ seems to relate to (old?) Inktank/Ceph websites, not Gluster. I could not find a similar page under https://github.com/gluster/glusterweb/tree/951ae79b/source , otherwise I would have pointed to the previous text that was (was there?) on gluster.org.

**Comment by amye** [comment]
We're in process of resolving this with legal, updated with Red Hat ToS. Thanks for the catch!
