### ISSUE TITLE
Robots.txt is too restrictive

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#155]
Following last issue ( #154 ), I tried to run linkchecker, but it seems to fail due to the current robots.txt, who seems to be slightly restrictive:

```
 $ curl https://www.gluster.org/robots.txt
User-agent: *
Disallow: /
```

Could we open it it up a bit for linkchecker to work ?

**Comment by mscherer** [comment]
So a side effect of the restriction is also that Google and others are likely to remove the website from their index. Can it be given a bit more consideration ?

**Comment by mscherer** [comment]
Still valid

**Comment by amye** [comment]
This is set by the hosting company. 
What would be the preferred setting?

**Comment by mscherer** [comment]
it is up to the person responsible for the web presence to decide what should be indexed or not. 

But looking at wpengine documentation: https://wpengine.com/support/read-use-robots-txt/ I would go for the 2nd. 

Or following another resource ( http://www.robotstxt.org/robotstxt.html ), maybe:
```
User-agent: *
Disallow:
```
is the simplest. 

Right now, the fact that Google do not index the website reduce outreach for the blog, and likely worsen the issue of doc not being well found as reported on 
https://github.com/gluster/community/issues/17

**Comment by amye** [comment]
Updated, disallowed from the wp-admin page.
