### ISSUE TITLE
No explanation of what change when something is EOL on the web page

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#157]
So, while looking on https://www.gluster.org/release-schedule/ , I started to wonder what EOL mean, and there is no explanation on it anywehre. 

For example, does that mean we will remove content from the download server, does that mean that all bugs are gonna be closed and/or considered, that documentation is gonna be cleaned up ?

As we have people coming on IRC with EOL version, a clear text to set expectation and to be able to give to people would greatly help on that front.

**Comment by amye** [comment]
Adding @ShyamsundarR @vbellur -  I don't think we have a process currently written down for 'what happens to deprecated versions'. And we should!

**Comment by amye** [comment]
Adding to TLC agenda for week of June 11th.

**Comment by amye** [comment]
Resolved with new release schedule.
