### ISSUE TITLE
Rework "gluster consultancies" from https://www.gluster.org/community/

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#160]
So, while I do not want to say that consultancies are not part of the community, I think that this part of the page do not bring anything useful to the reader, since that's just a recap of what is Gluster (in the middle of the page ), and not related to the title of that sub part, nor the topic (community).

**Comment by mscherer** [comment]
It seems that a different but similar sounding text is on the bottom of https://www.gluster.org/roadmap/

**Comment by amye** [comment]
Edited to say 'about Gluster', and yes, this is duplicated on roadmap.
