### ISSUE TITLE
Button "Contribute!" as show on blog post do not work

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#164]
For example on https://www.gluster.org/use-dnsmasq-for-separating-dns-queries/

The button on the right ("Contribute!") do link to https://www.gluster.org/community/contribute/ 

This is a page that no longer exist and so a 404 page

**Comment by amye** [comment]
Resolved with a redirect to community page, but we should build out a direct contributors guide: how to submit a patch? Guide to your first contribution? Or move our 'easy fix' list here?

**Comment by mscherer** [comment]
Closing, since this was resolved.
