### ISSUE TITLE
Duplicated tag in the DB

### ISSUE THREAD

**Issue by mscherer** [gluster/glusterweb#165]
For a reason that I do not truly understand, there seems to have duplicated tags in the DB, as seen by scrolling any blog post. 

For example:
https://www.gluster.org/?s=netbsd

I see cloud twice, events twice, several variation of "file systems", 2 KVM, 2 planet, 2 open source, 2 "puppet", Red hat and redhat, Screencast and screencasts and maybe others. 

So variation are caused by the aggregation on the planet side and likely can't be fixed. But duplicate tags are weirder, so I wonder if there is some change in case somewhere down the line that do result in a bug.

**Comment by amye** [comment]
There was an error in the tag import, they've been imported twice. 
Want to help clean it up?

**Comment by jasonbrooks** [comment]
I deleted all of the empty categories, of which there were many. That took care of most of the dupes, and then I deduped the rest. I think we can close this one, but it might be worth thinking about the categores / tags structure in here moving forward.
