### ISSUE TITLE
gluster.org/blog redirects to an old blog post

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterweb#171]
The 'News' menu on the website links to 'Gluster.org Blog' with the URL https://www.gluster.org/blog .
Instead of landing on the first page of the blog, users are redirected to an old blog post at https://www.gluster.org/blog-post-1-source-build-and-install/ 

This redirection must be fixed, or the link needs to be removed from the website.

**Comment by amye** [comment]
This is a stupid 'feature' that comes with WordPress, it autocompletes when it doesn't have a post that matches exactly. I'll just make a page that displays all posts, like it's supposed to be.
