### ISSUE TITLE
SSL Certificate served for gluster.org does not match the domain name

### ISSUE THREAD

**Issue by garrett** [gluster/glusterweb#33]
There's an invalid certificate for gluster.org. I do see that https://www.gluster.org/ does work, so it's a redirction problem with how gluster.org is set up.

**Comment by mscherer** [comment]
This will be fixed once we switch to letsencrypt, which will happen once we switch to ansible for that server.

**Comment by amye** [comment]
Hey @mscherer, just making sure you haven't forgotten about this.
Thanks!

**Comment by mscherer** [comment]
I should give a try, but when we did the switch on rdo for the same kind of issue, this did broke a bit too much stuff to my taste due to a combination of ansible bugs and specific trick I did use (I think the bugs were fixed however in 2.1, so it should be ok now).

**Comment by mscherer** [comment]
Mhh, so there is no certbot package for supercolony. So this will be fixed when we upgrade the server to EL7. I will defer that after the migration of the VMs.
