### ISSUE TITLE
System Admin guide URL 404

### ISSUE THREAD

**Issue by Lewiscowles1986** [gluster/glusterweb#71]
System Admin guide URL should be

http://gluster.readthedocs.org/en/latest/Administrator%20Guide/

not 

http://gluster.readthedocs.org/en/latest/Administrator%20Guide/README/

this is from 

https://www.gluster.org/

**Comment by nixpanic** [comment]
@amye you know how and where to fix links on the webpage, right?

**Comment by amye** [comment]
Sure do. Will take care of this.

**Comment by nixpanic** [comment]
Thanks @amye , when you look into this, please check [bug 1324467](https://bugzilla.redhat.com/show_bug.cgi?id=1324467) too.

**Comment by Lewiscowles1986** [comment]
would it be possible for you to let me know too? I had a look earlier but couldn't find it so I couldn't create a PR

**Comment by amye** [comment]
Follow up: 
All of the top links live in /source/layouts/_navbar_static_top.haml, which is not easy to find. 
I've submitted a PR for it, will wait until tests pass to merge.
