### ISSUE TITLE
Favicon seems wrong for Gluster website

### ISSUE THREAD

**Issue by justinclift** [gluster/glusterweb#9]
Just noticed that the Gluster website doesn't seem to have a working favicon.ico.  Is that a known problem?

**Comment by justinclift** [comment]
This looks like the URL that should be updated:https://github.com/gluster/glusterweb/blob/master/source/images/favicon_base.png  (thanks @nixpanic)

**Comment by tigert** [comment]
This is a known issue yeah, need to move it over from the old site.

**Comment by tigert** [comment]
fixed that now.

**Comment by tigert** [comment]
thanks for reporting :-)

**Comment by justinclift** [comment]
Maybe I'm doing something wrong... but there's no favicon.ico loading at all for me now.  (tried both Opera, and latest Firefox.  Both on OSX).

**Comment by tigert** [comment]
I don't have a mac, but on my ipad the icon does show - though I noticed the icon does not support transparency (maybe because the icons in ios are those rounded rectangles) so I need to make that opaque.

But maybe osx looks for something different there..?

**Comment by jasonbrooks** [comment]
The favicon seems fine on Chrome/Fedora 23 Firefox/Fedora 23

**Comment by justinclift** [comment]
Tried it just now with Firefox on Windows, and it has the correct leaf looking icon. :wink:
